import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Clock3, Mail, Plus, Trash2, Users } from "lucide-react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import PageHeader from "../components/PageHeader";
import { Alert, Loading } from "../components/Feedback";
import { apiFetch } from "../lib/api";
import { todayISO } from "../lib/format";
import { formatTimeOption, isSlotWithinOpeningHours, START_TIME_OPTIONS, TIME_OPTIONS } from "../lib/schedule";

const emptyParticipant = () => ({ nom: "", email: "" });
const initial = { nom_demandeur: "", email_demandeur: "", objet: "", date_reservation: todayISO(), heure_debut: "", heure_fin: "", id_salle: "", nombre_participants: 0, statut: "CONFIRMEE", notes: "", participants: [] };

export default function ReservationForm() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const [searchParams] = useSearchParams();
  const [form, setForm] = useState(() => editing ? initial : ({ ...initial, date_reservation: searchParams.get("date") || initial.date_reservation, heure_debut: searchParams.get("debut") || "", heure_fin: searchParams.get("fin") || "" })); const [rooms, setRooms] = useState([]); const [loading, setLoading] = useState(editing); const [checking, setChecking] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [availability, setAvailability] = useState("");
  useEffect(() => { if (!editing) return; apiFetch(`/reservations/${id}/`).then((r) => { if (r.statut === "ANNULEE") { navigate(`/reservations/${id}`, { replace: true }); return; } setForm({ ...initial, ...r, id_salle: String(r.id_salle), heure_debut: r.heure_debut?.slice(0, 5), heure_fin: r.heure_fin?.slice(0, 5), participants: r.participants || [] }); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, [editing, id, navigate]);
  // Après chaque changement de créneau, on attend 350 ms avant d'interroger
  // Django. Ce délai évite une requête réseau à chaque frappe dans l'heure.
  useEffect(() => {
    const slotIsInvalid = !form.date_reservation || !isSlotWithinOpeningHours(form.heure_debut, form.heure_fin);
    if (slotIsInvalid) {
      // Le prochain changement valide recalculera la liste ; on masque entre-temps
      // les résultats du créneau précédent pour éviter une sélection trompeuse.
      queueMicrotask(() => {
        setRooms([]);
        setAvailability(form.heure_debut && form.heure_fin ? "Choisissez un créneau entre 08h00 et 17h30, avec une heure de fin postérieure au début." : "");
        setForm((current) => current.id_salle ? { ...current, id_salle: "" } : current);
      });
      return undefined;
    }
    const timer = setTimeout(() => { setChecking(true); setAvailability(""); const qs = new URLSearchParams({ date: form.date_reservation, heure_debut: form.heure_debut, heure_fin: form.heure_fin }); if (editing) qs.set("exclure_reservation", id); apiFetch(`/salles/disponibles/?${qs}`).then((list) => { setRooms(list); setForm((current) => list.some((room) => String(room.id_salle) === String(current.id_salle)) ? current : { ...current, id_salle: "" }); setAvailability(list.length ? `${list.length} salle${list.length > 1 ? "s" : ""} disponible${list.length > 1 ? "s" : ""}` : "Aucune salle disponible sur ce créneau."); }).catch((e) => setAvailability(e.message)).finally(() => setChecking(false)); }, 350);
    return () => clearTimeout(timer);
  }, [form.date_reservation, form.heure_debut, form.heure_fin, editing, id]);
  const participantCount = useMemo(() => form.participants.filter((p) => p.email.trim()).length, [form.participants]);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const setStartTime = (value) => setForm((current) => ({
    ...current,
    heure_debut: value,
    // Une fin devenue antérieure au nouveau début doit être choisie à nouveau.
    heure_fin: current.heure_fin > value ? current.heure_fin : "",
  }));
  const setParticipant = (index, key, value) => setForm((current) => ({ ...current, participants: current.participants.map((p, i) => i === index ? { ...p, [key]: value } : p) }));
  // Le serveur détermine lui-même le RH connecté et le statut. React envoie
  // uniquement les données métier saisies dans le formulaire.
  const submit = async (event) => { event.preventDefault(); setError(""); if (!isSlotWithinOpeningHours(form.heure_debut, form.heure_fin)) { setError("Le créneau doit être compris entre 08h00 et 17h30."); return; } if (!form.id_salle) { setError("Sélectionnez une salle disponible."); return; } const participantEmails = form.participants.map((participant) => participant.email.trim().toLowerCase()).filter(Boolean); if (new Set(participantEmails).size !== participantEmails.length) { setError("Un même e-mail participant ne peut être ajouté qu’une seule fois."); return; } setSaving(true); const payload = { ...form, id_salle: Number(form.id_salle), nombre_participants: participantCount, participants: form.participants.filter((p) => p.email.trim()).map((p) => ({ nom: p.nom.trim(), email: p.email.trim() })) }; delete payload.id_utilisateur; delete payload.statut; try { await apiFetch(editing ? `/reservations/${id}/` : "/reservations/", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); navigate("/reservations", { replace: true, state: { success: editing ? "La réservation a été modifiée avec succès." : "La réservation a été créée avec succès." } }); } catch (e) { setError(e.message); window.scrollTo({ top: 0, behavior: "smooth" }); } finally { setSaving(false); } };
  if (loading) return <Loading label="Chargement de la réservation…" />;
  return <><PageHeader title={editing ? "Modifier la réservation" : "Nouvelle réservation"} description={editing ? "Les modifications déclencheront une nouvelle notification et recalculeront le rappel H-2." : "Renseignez la demande reçue par le service RH."}><Link to="/reservations" className="btn-secondary"><ArrowLeft size={17} /> Retour</Link></PageHeader>{error && <Alert onClose={() => setError("")}>{error}</Alert>}
    <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[1fr_340px]">
      <div className="space-y-6"><section className="card p-5 sm:p-6"><div className="mb-5"><h2 className="font-bold text-slate-900">Informations de la réunion</h2><p className="text-xs text-slate-500">Objet, demandeur et informations complémentaires</p></div><div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">Objet de la réunion *</label><input className="field" required value={form.objet} onChange={(e) => set("objet", e.target.value)} placeholder="Ex. Réunion de coordination chantier" /></div><div><label className="label">Nom du demandeur *</label><input className="field" required value={form.nom_demandeur} onChange={(e) => set("nom_demandeur", e.target.value)} placeholder="Nom et prénom" /></div><div><label className="label">E-mail du demandeur *</label><input className="field" required type="email" value={form.email_demandeur} onChange={(e) => set("email_demandeur", e.target.value)} placeholder="nom@uniservci.net" /></div><div className="sm:col-span-2"><label className="label">Notes</label><textarea className="field min-h-24 resize-y" value={form.notes || ""} onChange={(e) => set("notes", e.target.value)} placeholder="Matériel requis, consignes d’accès…" /></div></div></section>
      <section className="card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><div><h2 className="font-bold text-slate-900">Participants</h2><p className="text-xs text-slate-500">Ajoutez uniquement les personnes qui doivent recevoir l’invitation.</p></div><button type="button" className="btn-secondary text-sm" onClick={() => set("participants", [...form.participants, emptyParticipant()])}><Plus size={16} /> Ajouter</button></div><div className="space-y-3">{form.participants.map((p, i) => <div key={i} className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50/60 p-3 sm:grid-cols-[1fr_1.2fr_auto] sm:items-end"><div><label className="label">Nom</label><input className="field" value={p.nom || ""} onChange={(e) => setParticipant(i, "nom", e.target.value)} placeholder="Nom du participant" /></div><div><label className="label">E-mail *</label><input className="field" type="email" required value={p.email} onChange={(e) => setParticipant(i, "email", e.target.value)} placeholder="email@exemple.com" /></div><button type="button" aria-label="Retirer le participant" className="mb-0.5 rounded-lg p-3 text-slate-400 hover:bg-slate-200 hover:text-black" onClick={() => set("participants", form.participants.filter((_, index) => index !== i))}><Trash2 size={18} /></button></div>)}{!form.participants.length && <div className="rounded-xl border border-dashed border-slate-300 p-7 text-center text-sm text-slate-500"><Users className="mx-auto mb-2 text-slate-400" />Aucun participant pour le moment.</div>}</div></section></div>
      <aside className="space-y-5"><section className="card p-5"><h2 className="font-bold text-slate-900">Créneau et salle</h2><p className="mb-5 text-xs text-slate-500">Réservations possibles de 08h00 à 17h30, par créneaux de 30 minutes.</p><div className="space-y-4"><div><label className="label">Date *</label><input className="field" type="date" min={editing ? undefined : todayISO()} required value={form.date_reservation} onChange={(e) => set("date_reservation", e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Début *</label><select className="field" required value={form.heure_debut} onChange={(e) => setStartTime(e.target.value)}><option value="">Choisir</option>{START_TIME_OPTIONS.map((time) => <option key={time} value={time}>{formatTimeOption(time)}</option>)}</select></div><div><label className="label">Fin *</label><select className="field" required disabled={!form.heure_debut} value={form.heure_fin} onChange={(e) => set("heure_fin", e.target.value)}><option value="">Choisir</option>{TIME_OPTIONS.filter((time) => time > form.heure_debut).map((time) => <option key={time} value={time}>{formatTimeOption(time)}</option>)}</select></div></div><div><label className="label">Salle disponible *</label><select className="field" required disabled={!form.heure_fin || checking} value={form.id_salle} onChange={(e) => set("id_salle", e.target.value)}><option value="">{checking ? "Vérification…" : "Sélectionner une salle"}</option>{rooms.map((r) => <option key={r.id_salle} value={r.id_salle}>{r.nom_salle}{r.etage ? ` · ${r.etage}` : ""}</option>)}</select>{availability && <p className="mt-2 text-xs text-slate-600">{availability}</p>}</div></div></section>
      <section className="card p-5"><h3 className="text-sm font-bold text-slate-800">Récapitulatif</h3><div className="mt-4 space-y-3 text-sm"><p className="flex justify-between text-slate-500"><span className="flex items-center gap-2"><Users size={16} /> Participants</span><b className="text-slate-800">{participantCount}</b></p><p className="flex justify-between text-slate-500"><span className="flex items-center gap-2"><Clock3 size={16} /> Rappel</span><b className="text-slate-800">H-2</b></p><p className="flex justify-between text-slate-500"><span className="flex items-center gap-2"><Mail size={16} /> Notifications</span><b className="text-slate-800">Automatiques</b></p></div><button className="btn-primary mt-5 w-full" disabled={saving || checking}>{saving ? "Enregistrement…" : <><Check size={18} />{editing ? "Enregistrer" : "Confirmer la réservation"}</>}</button></section></aside>
    </form></>;
}
