import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, CalendarDays, ChevronLeft, ChevronRight, Eye, List, Plus, Search, X } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import PageHeader from "../components/PageHeader";
import { Alert, Empty, Loading } from "../components/Feedback";
import { apiFetch } from "../lib/api";
import { formatDate, formatTime, statusClass, statusLabel } from "../lib/format";

const today = new Date();
const MONTHS = ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"];
const WEEKDAYS = ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"];
const toISO = (year, month, day) => `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;

export default function Reservations() {
  const navigate = useNavigate();
  const searchInput = useRef(null);
  const [items, setItems] = useState([]), [rooms, setRooms] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [mode, setMode] = useState("calendar"), [year, setYear] = useState(today.getFullYear()), [month, setMonth] = useState(today.getMonth()), [showAllMonths, setShowAllMonths] = useState(false);
  const [room, setRoom] = useState(""), [status, setStatus] = useState(""), [query, setQuery] = useState(""), [selected, setSelected] = useState(null), [selectedDay, setSelectedDay] = useState(null);
  const load = useCallback(async () => { setLoading(true); try { const [reservations, salles] = await Promise.all([apiFetch("/reservations/"), apiFetch("/salles/")]); setItems(reservations); setRooms(salles.filter((item) => item.active !== false)); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);

  const filtered = useMemo(() => items.filter((reservation) => (!room || String(reservation.id_salle) === room) && (!status || reservation.statut === status) && (!query || [reservation.objet, reservation.nom_demandeur, reservation.salle_nom, reservation.created_by_name].some((value) => value?.toLowerCase().includes(query.toLowerCase())))), [items, room, status, query]);
  const years = useMemo(() => { const values = items.map((item) => Number(item.date_reservation.slice(0, 4))); const minimum = Math.min(today.getFullYear() - 2, ...values); const maximum = Math.max(today.getFullYear() + 3, ...values); return Array.from({ length: maximum - minimum + 1 }, (_, index) => minimum + index); }, [items]);
  const goToday = () => { setYear(today.getFullYear()); setMonth(today.getMonth()); setShowAllMonths(false); };
  const movePeriod = (amount) => { if (showAllMonths) { setYear(year + amount); return; } const next = new Date(year, month + amount, 1); setYear(next.getFullYear()); setMonth(next.getMonth()); };
  const openMonth = (selectedMonth) => { setMonth(selectedMonth); setShowAllMonths(false); };

  return <><PageHeader title="Réservations" description="Calendrier mensuel partagé et historique des réservations."><button className="btn-secondary" onClick={() => navigate(-1)}><ArrowLeft size={17} />Retour</button><Link className="btn-primary" to="/reservations/nouvelle"><Plus size={18} />Nouvelle réservation</Link></PageHeader>
    {error && <Alert onClose={() => setError("")}>{error}</Alert>}
    <div className="card mb-5 space-y-3 p-4"><div className="flex flex-wrap items-center gap-3"><button className="btn-secondary" onClick={goToday}>Aujourd’hui</button><div className="flex shrink-0 overflow-hidden rounded-xl border border-slate-200 bg-white" role="group" aria-label="Navigation du calendrier"><button type="button" aria-label="Période précédente" title="Période précédente" className="grid size-12 place-items-center border-r border-slate-200 text-slate-700 transition hover:bg-slate-100" onClick={() => movePeriod(-1)}><ChevronLeft size={20} /></button><button type="button" aria-label="Période suivante" title="Période suivante" className="grid size-12 place-items-center text-slate-700 transition hover:bg-slate-100" onClick={() => movePeriod(1)}><ChevronRight size={20} /></button></div>{!showAllMonths && <div className="w-44"><select aria-label="Sélectionner le mois" className="field font-bold" value={month} onChange={(event) => setMonth(Number(event.target.value))}>{MONTHS.map((label, index) => <option key={label} value={index}>{label}</option>)}</select></div>}<div className="w-32"><select aria-label="Sélectionner l’année" className="field text-center font-black" value={year} onChange={(event) => setYear(Number(event.target.value))}>{years.map((value) => <option key={value}>{value}</option>)}</select></div><label className="flex cursor-pointer items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold"><input type="checkbox" checked={showAllMonths} onChange={(event) => setShowAllMonths(event.target.checked)} />Afficher les 12 mois</label><div className="ml-auto flex rounded-lg bg-slate-100 p-1"><button onClick={() => setMode("calendar")} className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-bold ${mode === "calendar" ? "bg-white shadow" : "text-slate-500"}`}><CalendarDays size={17} />Calendrier</button><button onClick={() => setMode("list")} className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm font-bold ${mode === "list" ? "bg-white shadow" : "text-slate-500"}`}><List size={17} />Liste</button></div></div>
      <div className="grid gap-3 md:grid-cols-[1fr_220px_190px]"><div className="relative"><button type="button" aria-label="Activer la recherche" onClick={() => searchInput.current?.focus()} className="absolute left-1.5 top-1/2 z-10 grid size-9 -translate-y-1/2 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-black"><Search size={18} /></button><input ref={searchInput} type="search" className="field !pl-12 !pr-12" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Objet, demandeur, salle ou créateur…" />{query && <button type="button" aria-label="Effacer la recherche" onClick={() => { setQuery(""); searchInput.current?.focus(); }} className="absolute right-1.5 top-1/2 z-10 grid size-9 -translate-y-1/2 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-black"><X size={16} /></button>}</div><select className="field" value={room} onChange={(event) => setRoom(event.target.value)}><option value="">Toutes les salles</option>{rooms.map((item) => <option key={item.id_salle} value={item.id_salle}>{item.nom_salle}</option>)}</select><select className="field" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tous les statuts</option><option value="CONFIRMEE">Confirmées</option><option value="ANNULEE">Annulées</option><option value="EN_ATTENTE">En attente</option></select></div></div>
    {loading ? <div className="card"><Loading /></div> : mode === "calendar" ? showAllMonths ? <YearCalendar year={year} items={filtered} onSelectDay={setSelectedDay} onSelectMonth={openMonth} /> : <MonthCalendar year={year} month={month} items={filtered} onSelectDay={setSelectedDay} /> : <ListView items={filtered} onSelect={setSelected} />}
    {selectedDay && <DayReservations day={selectedDay} onClose={() => setSelectedDay(null)} onSelect={(reservation) => { setSelectedDay(null); setSelected(reservation); }} />}
    {selected && <Detail reservation={selected} onClose={() => setSelected(null)} />}
  </>;
}

function MonthCalendar({ year, month, items, onSelectDay }) {
  const dayCount = new Date(year, month + 1, 0).getDate();
  const leading = (new Date(year, month, 1).getDay() + 6) % 7;
  const cells = [...Array(leading).fill(null), ...Array.from({ length: dayCount }, (_, index) => index + 1)];
  while (cells.length % 7) cells.push(null);
  const todayISO = toISO(today.getFullYear(), today.getMonth(), today.getDate());
  return <section className="card overflow-x-auto"><div className="min-w-[1050px]"><div className="border-b p-7 text-center"><p className="text-xs font-black uppercase tracking-[.25em] text-slate-400">Calendrier partagé</p><h2 className="mt-1 text-4xl font-black">{MONTHS[month]} {year}</h2></div><div className="grid grid-cols-7 border-b bg-slate-50">{WEEKDAYS.map((day, index) => <div key={day} className={`border-r p-4 text-center text-sm font-black uppercase ${index > 4 ? "text-red-500" : "text-slate-500"}`}>{day}</div>)}</div><div className="grid grid-cols-7">{cells.map((day, index) => { if (!day) return <div key={`empty-${index}`} className="min-h-48 border-b border-r bg-slate-50/60" />; const iso = toISO(year, month, day); const reservations = items.filter((item) => item.date_reservation === iso).sort((a, b) => a.heure_debut.localeCompare(b.heure_debut)); return <MonthDay key={iso} day={day} iso={iso} weekend={index % 7 > 4} isToday={iso === todayISO} reservations={reservations} onSelectDay={onSelectDay} />; })}</div></div></section>;
}

function MonthDay({ day, iso, weekend, isToday, reservations, onSelectDay }) {
  return <button onClick={() => reservations.length && onSelectDay({ iso, reservations })} className={`group relative min-h-48 border-b border-r p-3 text-left transition ${isToday ? "bg-blue-50" : "bg-white"} ${reservations.length ? "hover:z-10 hover:bg-red-50 hover:shadow-xl" : ""}`}><span className={`grid size-9 place-items-center rounded-full text-base font-black ${isToday ? "bg-black text-white" : weekend ? "text-red-500" : "text-slate-700"}`}>{day}</span><div className="mt-3 space-y-2">{reservations.slice(0, 3).map((reservation) => <span key={reservation.id_reservation} className={`block rounded-lg border p-2 text-[11px] shadow-sm ${reservation.statut === "ANNULEE" ? "border-slate-200 bg-slate-100 text-slate-500" : "border-black bg-black text-white"}`}><b className="block truncate">{reservation.objet}</b><span className="block truncate opacity-80">{formatTime(reservation.heure_debut)} – {formatTime(reservation.heure_fin)}</span><small className="block truncate opacity-70">Par {reservation.created_by_name || "Service RH"}</small></span>)}{reservations.length > 3 && <span className="block rounded-md bg-red-100 px-2 py-1 text-[10px] font-black text-red-700">+ {reservations.length - 3} autre(s)</span>}</div>{reservations.length > 0 && <span className="pointer-events-none absolute -right-2 -top-2 hidden rounded-full bg-red-500 px-2 py-1 text-[10px] font-black text-white shadow-lg group-hover:block">{reservations.length} réservation(s)</span>}</button>;
}

function YearCalendar({ year, items, onSelectDay, onSelectMonth }) {
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-7 flex items-end justify-between border-b border-slate-100 pb-5"><div><p className="text-xs font-black uppercase tracking-[.25em] text-slate-400">Calendrier partagé</p><h2 className="mt-1 text-4xl font-black">{year}</h2></div><p className="text-xs text-slate-500">Cliquez sur un mois pour l’ouvrir</p></div><div className="grid gap-x-8 gap-y-10 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{MONTHS.map((label, selectedMonth) => <MiniMonth key={label} year={year} month={selectedMonth} label={label} items={items} onSelectDay={onSelectDay} onSelectMonth={onSelectMonth} />)}</div></section>;
}

function MiniMonth({ year, month, label, items, onSelectDay, onSelectMonth }) {
  const dayCount = new Date(year, month + 1, 0).getDate();
  const leading = (new Date(year, month, 1).getDay() + 6) % 7;
  const cells = [...Array(leading).fill(null), ...Array.from({ length: dayCount }, (_, index) => index + 1)];
  while (cells.length % 7) cells.push(null);
  const todayISO = toISO(today.getFullYear(), today.getMonth(), today.getDate());
  return <article><button onClick={() => onSelectMonth(month)} className="mb-3 w-full text-center text-sm font-black uppercase tracking-[.18em] text-slate-800 hover:text-red-600">{label}</button><div className="grid grid-cols-7">{WEEKDAYS.map((day, index) => <div key={day} className={`pb-2 text-center text-[9px] font-black uppercase ${index > 4 ? "text-red-500" : "text-slate-400"}`}>{day.slice(0, 1)}</div>)}{cells.map((day, index) => { if (!day) return <span key={`empty-${index}`} className="aspect-square" />; const iso = toISO(year, month, day); const reservations = items.filter((item) => item.date_reservation === iso); const hasReservations = reservations.length > 0; const title = reservations.map((item) => `${item.objet} — ${item.created_by_name || "Service RH"}`).join("\n"); return <button key={iso} disabled={!hasReservations} title={title || undefined} onClick={() => hasReservations && onSelectDay({ iso, reservations })} className={`relative grid aspect-square place-items-center rounded-full text-[11px] font-bold transition ${iso === todayISO ? "bg-black text-white" : hasReservations ? "bg-red-50 text-red-700 hover:bg-red-500 hover:text-white" : index % 7 > 4 ? "text-red-400" : "text-slate-700"}`}>{day}{hasReservations && <span className={`absolute bottom-0.5 size-1.5 rounded-full ${iso === todayISO ? "bg-red-400" : "bg-red-500"}`} />}{reservations.length > 1 && <span className="absolute -right-0.5 -top-0.5 grid size-4 place-items-center rounded-full bg-black text-[8px] text-white">{reservations.length}</span>}</button>; })}</div></article>;
}

function DayReservations({ day, onClose, onSelect }) {
  return <div className="fixed inset-0 z-60 grid place-items-center bg-black/50 p-4" onClick={onClose}><section className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="mb-5 flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Réservations du jour</p><h2 className="mt-1 text-2xl font-black">{formatDate(day.iso, { weekday: "long" })}</h2></div><button className="rounded-lg p-2 hover:bg-slate-100" onClick={onClose}><X /></button></div><div className="space-y-3">{day.reservations.sort((a, b) => a.heure_debut.localeCompare(b.heure_debut)).map((reservation) => <button key={reservation.id_reservation} onClick={() => onSelect(reservation)} className="block w-full rounded-xl border border-slate-200 p-4 text-left transition hover:border-black hover:bg-slate-50"><div className="flex items-start justify-between gap-4"><div><b className="text-base">{reservation.objet}</b><p className="mt-1 text-sm text-slate-500">{formatTime(reservation.heure_debut)} – {formatTime(reservation.heure_fin)} · {reservation.salle_nom}</p><p className="mt-2 text-xs font-bold">Réservation effectuée par {reservation.created_by_name || "Service RH"}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold ${statusClass(reservation.statut)}`}>{statusLabel(reservation.statut)}</span></div></button>)}</div></section></div>;
}

function ListView({ items, onSelect }) { const sorted = [...items].sort((a, b) => `${b.date_reservation}${b.heure_debut}`.localeCompare(`${a.date_reservation}${a.heure_debut}`)); return <div className="card overflow-x-auto">{!sorted.length ? <Empty>Aucune réservation.</Empty> : <table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Réunion</th><th className="p-4">Date et heure</th><th className="p-4">Salle</th><th className="p-4">Créée par</th><th className="p-4">Statut</th><th className="p-4" /></tr></thead><tbody className="divide-y">{sorted.map((reservation) => <tr key={reservation.id_reservation}><td className="p-4 font-bold">{reservation.objet}<small className="block font-normal text-slate-500">{reservation.nom_demandeur}</small></td><td className="p-4">{formatDate(reservation.date_reservation)}<small className="block text-slate-500">{formatTime(reservation.heure_debut)} – {formatTime(reservation.heure_fin)}</small></td><td className="p-4">{reservation.salle_nom}</td><td className="p-4">{reservation.created_by_name || "Ancienne donnée"}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusClass(reservation.statut)}`}>{statusLabel(reservation.statut)}</span></td><td className="p-4"><button onClick={() => onSelect(reservation)} className="p-2"><Eye size={18} /></button></td></tr>)}</tbody></table>}</div>; }

function Detail({ reservation, onClose }) { return <div className="fixed inset-0 z-60 flex justify-end bg-black/40" onClick={onClose}><aside className="h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><button className="float-right p-2" onClick={onClose}><X /></button><p className="text-xs font-bold uppercase text-slate-400">Détail de la réservation</p><h2 className="mt-2 pr-10 text-2xl font-black">{reservation.objet}</h2><div className="mt-6 space-y-4 text-sm"><p><b>Date et créneau</b><br />{formatDate(reservation.date_reservation)} · {formatTime(reservation.heure_debut)} – {formatTime(reservation.heure_fin)}</p><p><b>Salle</b><br />{reservation.salle_nom}</p><p><b>Demandeur</b><br />{reservation.nom_demandeur} · {reservation.email_demandeur}</p><hr /><h3 className="font-black">Traçabilité</h3><Trace label="Créée" name={reservation.created_by_name} date={reservation.created_at} /><Trace label="Modifiée" name={reservation.updated_by_name} date={reservation.updated_at} /><Trace label="Annulée" name={reservation.cancelled_by_name} date={reservation.cancelled_at} /></div><div className="mt-8 flex gap-2"><Link className="btn-secondary" to={`/reservations/${reservation.id_reservation}`}>Voir la fiche</Link>{reservation.statut !== "ANNULEE" && <Link className="btn-primary" to={`/reservations/${reservation.id_reservation}/modifier`}>Modifier</Link>}</div></aside></div>; }
function Trace({ label, name, date }) { return <p className="rounded-lg bg-slate-50 p-3"><b>{label}</b><br /><span>{name || "Non renseigné"}</span>{date && <small className="block text-slate-500">{new Date(date).toLocaleString("fr-FR")}</small>}</p>; }
